// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreateAssignmentController from "./create_assignment_controller"
application.register("create-assignment", CreateAssignmentController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SortableRolesController from "./sortable_roles_controller"
application.register("sortable-roles", SortableRolesController)
